name: Publish image

on:
  push:
    branches: [ main ]

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push ${{ env.DOCKER_IMAGE_MAIN_STAGE }}
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.DOCKER_IMAGE_MAIN_STAGE }}
        target: ${{ env.DOCKER_IMAGE_MAIN_STAGE }}